repos:
  - repo: local
    hooks:
      - id : black
        name : black
        entry : black
        language : system
        args :
          - '--config'
          - 'linters_code/black/pyproject.toml'  # Path to your config file
        files : '\.py$'
        stages : [ pre-commit ]

      - id : bandit
        name : bandit
        entry : bandit
        language : system
        args :
          - '-r'
          - '-c'
          - 'linters_code/bandit/bandit.yaml'
        stages : [ pre-push ]

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        args:
          - '--rcfile=linters_code/pylint/.pylintrc'
          - 'application'
          - 'btg'
          - 'config'
        stages: [pre-push]
