repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        args:
          - '--config'
          - 'linters_code/black/pyproject.toml'
          - 'application'
          - 'btg'
          - 'config'
        stages: [pre-commit]

      - id: bandit
        name: bandit
        entry: bandit
        language: system
        args:
          - '-r'
          - 'application'
          - 'btg'
          - 'config'
          - '-c'
          - 'linters_code/bandit/bandit_config.json'
        stages: [pre-push]

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        args:
          - '--rcfile=linters_code/pylint/.pylintrc'
          - 'application'
          - 'btg'
          - 'config'
        stages: [pre-push]
