services:
  app:
    build:
      context: ./dockerfile
      dockerfile: Dockerfile
    container_name: btg_app
    working_dir: /server
    ports:
      - "8000:8000"
    command:
      - ./config/script_init.sh
    environment:
      MONGO_URL: "mongodb://root:example@mongodb:27017/"
      PYTHONPATH: "/server/"
      TZ: "America/Bogota"
    depends_on:
      - mongodb
    volumes:
      - ./application:/server/app
      - ./btg:/server/btg
      - ./config:/server/config

  mongodb:
    image: mongo:6.0
    container_name: btg_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # MongoDB root user
      MONGO_INITDB_ROOT_PASSWORD: example  # MongoDB root password
      TZ: "America/Bogota"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: btg_mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root  # MongoDB admin user
      ME_CONFIG_MONGODB_ADMINPASSWORD: example  # MongoDB admin password
      ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongodb:27017/"  # MongoDB connection URL
      ME_CONFIG_BASICAUTH_USERNAME: admin  # Basic Auth username for Mongo Express
      ME_CONFIG_BASICAUTH_PASSWORD: newpassword  # Basic Auth password for Mongo Express
      TZ: "America/Bogota"

volumes:
  mongo_data:
