[tool.black]
line-length = 88
target-version = ['py310']
include = '(application|btg|config)/.*\.py$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | __pycache__
  | \.svn
  | \.bzr
  | build
  | dist
  | scripts
  | .*\.pyc
  | script_init\.sh
  | poetry\.lock
  | pyproject\.toml
)/
'''
